databases:
  - name: postgres
    ipAllowList: []
    databaseName: ticketfusion_upsi
    user: ticketfusion_upsi_user

services:
  - type: web
    name: ticketfusion_upsi
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false