MPESA_CONSUMER_KEY: '3kB1F1QofGpcccqDudXPLR2a2GkcWGwJS8EYJAWXWF8ouydC'
MPESA_CONSUMER_SECRET: 'uGegPwLF23WEQn3VpVm8RSawfaznqywyBrDSD3BT9qTSpaIlWpT1pxWn1sjKGdla'
MPESA_PASSKEY: 'bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919'
MPESA_SHORT_CODE: '174379'
MPESA_INITIATOR_NAME: 'testapi'
MPESA_INITIATOR_PASSWORD: 'Safaricom999!*!'
CALLBACK_URL: 'https://16d6-196-201-224-252.ngrok-free.app'
REGISTER_URL: "https://sandbox.safaricom.co.ke/mpesa/c2b/v1/registerurl"