MPESA_CONSUMER_KEY: 'TgNzDH9LFSeeHNJO4Umcck1R8iCABNu4u7cIta9lDktnAPR5'
MPESA_CONSUMER_SECRET: 't7pZ1V6E7cUKMATzDhjMtJWy6GiRVRDyEMffpFZID5hUbMs8WjVGmGIfTgnCKiza'
MPESA_PASSKEY: '1a775fee0e96d0f01a67ce97ce8cfba6b7af862821c0b94785b22079ec95a96b'
MPESA_SHORT_CODE: '5263162'
# MPESA_INITIATOR_NAME: 'testapi'
# MPESA_INITIATOR_PASSWORD: 'Safaricom999!*!'
CALLBACK_URL: 'https://1490-196-201-224-252.ngrok-free.app '
# REGISTER_URL: "https://sandbox.safaricom.co.ke/mpesa/c2b/v1/registerurl"

# MPESA_CONSUMER_SECRET=t7pZ1V6E7cUKMATzDhjMtJWy6GiRVRDyEMffpFZID5hUbMs8WjVGmGIfTgnCKiza
# MPESA_CONSUMER_KEY=TgNzDH9LFSeeHNJO4Umcck1R8iCABNu4u7cIta9lDktnAPR5
# MPESA_PASSKEY=1a775fee0e96d0f01a67ce97ce8cfba6b7af862821c0b94785b22079ec95a96b
# MPESA_SHORT_CODE=5263162
# CALLBACK_URL=  https://1490-196-201-224-252.ngrok-free.app 